apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nodejsappskube
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nodejsappskube
    spec:
      containers:
      - name: nodejsappskube
        image: $ACR_DNS/projectname:$BUILD_ID
        ports:
        - containerPort: 3000
        env:
        - name: HOST
          value: db_hostname
        - name: AUTH_KEY
          value: db_primarykey
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsappskube
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: nodejsappskube
---
